name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-interaction --no-dev

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.0'

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Yarn dependencies
        run: yarn install

      - name: Create package_build folder
        run:
          mkdir package_build

      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r package_build/crypto-blocks.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md Makefile Dockerfile docker-compose.yml yarn.lock webpack.config.js prepare.js package.json api_helper.txt README.md entrypoint.sh ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** src** node_modules** package_build**
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: crypto-blocks
          path: package_build/crypto-blocks.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: package_build/crypto-blocks.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}